version: "3.9"
services:
  sonarqube:
    container_name: sonar
    image: sonarqube:lts-community
    environment:
      SONAR_JDBC_USERNAME: ${DB_USER}@${DB_NAME}
      SONAR_JDBC_PASSWORD: ${DB_PASS}
      SONAR_JDBC_URL: jdbc:postgresql://${DB_IP}:5432/postgres?sslmode=require
    ports:
      - 9000:9000
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - sonarnet
    restart: always

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

networks:
  sonarnet:
    driver: bridge
